tap "homebrew/services"
brew "curl"
brew "fd"
brew "fzf"
brew "git"
brew "lazygit"
brew "sqlite"
brew "llm"
brew "mise"
brew "neovim"
brew "ollama", restart_service: :changed
brew "ripgrep"
brew "stow"
brew "tmux"
cask "1password-cli"
cask "iterm2"
cask "notion"
